import { LookaheadTask, ConstraintType, ConstraintStatus, WeatherForecast, CrewMember } from './types';

export const MOCK_PROJECT_CREW: CrewMember[] = [
  { id: 'c1', name: 'Daniel Mac', title: 'Site Supervisor', email: 'danielmac07@yopmail.com', phone: '+1999555678' },
  { id: 'c2', name: 'Heller Dell', title: 'Site Supervisor', email: 'heller@yopmail.com', phone: '+1-999555778' },
  { id: 'c3', name: 'Jodi Hubbard', title: 'Field Crew', email: 'jodih1898@yopmail.com', phone: '+1453555150' },
  { id: 'c4', name: 'Kelly Sharp', title: 'Field Crew', email: 'kellys6966@yopmail.com', phone: '+1723555824' },
  { id: 'c5', name: 'Kimberly Hoover', title: 'Foreman', email: 'kimberlyh3339@yopmail.com', phone: '+1667555012' },
  { id: 'c6', name: 'Lisa Blair', title: 'Scheduler', email: 'lisab2968@yopmail.com', phone: '+1837555858' },
  { id: 'c7', name: 'Nathan Singh', title: 'Field Crew', email: 'nathans1915@yopmail.com', phone: '+1086555752' },
  { id: 'c8', name: 'Sean Douglas', title: 'Crew', email: 'seand2053@yopmail.com', phone: '+1 940555725' },
  { id: 'c9', name: 'Steven Mitchell', title: 'Field Crew', email: 'stevenm0285@yopmail.com', phone: '+1404555343' },
  { id: 'c10', name: 'Susan Thomas', title: 'Foreman', email: 'susant2544@yopmail.com', phone: '+1145555544' },
];

/** Contractor names for "our" company (GC); crew can only be added to tasks from these */
export const PROJECT_COMPANY_NAMES = ['Martinez DevelopmentS'];

/** Predefined rejection reasons when SC cannot commit (Unanswered RFI auto-flags as project risk). */
export const REJECTION_REASONS = [
  { code: 'unanswered_rfi', label: 'Unanswered RFI' },
  { code: 'material_not_available', label: 'Material not available' },
  { code: 'equipment_not_available', label: 'Equipment not available' },
  { code: 'crew_not_available', label: 'Crew not available' },
  { code: 'other', label: 'Other' },
] as const;
export const REJECTION_REASON_UNANSWERED_RFI = 'unanswered_rfi';

/** Expanded rejection / propose-reason list used in the SC In-Review modal (9 categories). */
export const SC_REJECTION_REASONS = [
  { code: 'unanswered_rfi', label: 'Unanswered RFI' },
  { code: 'material_not_available', label: 'Material not available' },
  { code: 'equipment_not_available', label: 'Equipment not available' },
  { code: 'crew_not_available', label: 'Crew not available' },
  { code: 'predecessor_incomplete', label: 'Predecessor task incomplete' },
  { code: 'site_access', label: 'Site access not ready' },
  { code: 'design_revision', label: 'Design / drawing revision pending' },
  { code: 'safety_concern', label: 'Safety concern' },
  { code: 'other', label: 'Other' },
] as const;
export const SC_REJECTION_REASON_OTHER = 'other';

export const PPC_DATA = [82, 85, 78, 88, 92, 90]; // Last 6 weeks

export const MOCK_WEATHER: WeatherForecast[] = [
    { date: '2026-01-15', icon: 'sun', temp: 65 },
    { date: '2026-01-16', icon: 'sun', temp: 68 },
    { date: '2026-01-17', icon: 'cloud', temp: 66 },
    { date: '2026-01-18', icon: 'cloud', temp: 64 },
    { date: '2026-01-19', icon: 'rain', temp: 60 },
    { date: '2026-01-20', icon: 'rain', temp: 58 },
    { date: '2026-01-21', icon: 'cloud', temp: 62 },
    { date: '2026-01-22', icon: 'sun', temp: 67 },
    { date: '2026-01-23', icon: 'sun', temp: 70 },
    { date: '2026-01-24', icon: 'sun', temp: 71 },
    { date: '2026-01-25', icon: 'cloud', temp: 69 },
    { date: '2026-01-26', icon: 'cloud', temp: 68 },
    { date: '2026-01-27', icon: 'rain', temp: 65 },
    { date: '2026-01-28', icon: 'sun', temp: 69 },
    { date: '2026-01-29', icon: 'sun', temp: 70 },
    { date: '2026-01-30', icon: 'sun', temp: 72 },
    { date: '2026-01-31', icon: 'cloud', temp: 68 },
    { date: '2026-02-01', icon: 'sun', temp: 65 },
    { date: '2026-02-02', icon: 'sun', temp: 68 },
    { date: '2026-02-03', icon: 'cloud', temp: 66 },
    { date: '2026-02-04', icon: 'cloud', temp: 64 },
    { date: '2026-02-05', icon: 'rain', temp: 60 },
    { date: '2026-02-06', icon: 'rain', temp: 58 },
    { date: '2026-02-07', icon: 'cloud', temp: 62 },
    { date: '2026-02-08', icon: 'sun', temp: 67 },
    { date: '2026-02-09', icon: 'sun', temp: 70 },
    { date: '2026-02-10', icon: 'sun', temp: 71 },
    { date: '2026-02-11', icon: 'cloud', temp: 69 },
    { date: '2026-02-12', icon: 'cloud', temp: 68 },
    { date: '2026-02-13', icon: 'rain', temp: 65 },
    { date: '2026-02-14', icon: 'sun', temp: 69 },
    { date: '2026-02-15', icon: 'sun', temp: 70 },
    { date: '2026-02-16', icon: 'sun', temp: 72 },
    { date: '2026-02-17', icon: 'cloud', temp: 68 },
    { date: '2026-02-18', icon: 'sun', temp: 70 },
    { date: '2026-02-19', icon: 'sun', temp: 71 },
    { date: '2026-02-20', icon: 'cloud', temp: 69 },
    { date: '2026-02-21', icon: 'cloud', temp: 68 },
    { date: '2026-02-22', icon: 'rain', temp: 65 },
    { date: '2026-02-23', icon: 'sun', temp: 69 },
    { date: '2026-02-24', icon: 'sun', temp: 70 },
    { date: '2026-02-25', icon: 'cloud', temp: 68 },
    { date: '2026-02-26', icon: 'cloud', temp: 67 },
    { date: '2026-02-27', icon: 'rain', temp: 64 },
    { date: '2026-02-28', icon: 'sun', temp: 68 },
    { date: '2026-03-01', icon: 'sun', temp: 70 },
    { date: '2026-03-02', icon: 'sun', temp: 72 },
    { date: '2026-03-03', icon: 'cloud', temp: 71 },
    { date: '2026-03-04', icon: 'cloud', temp: 70 },
    { date: '2026-03-05', icon: 'rain', temp: 68 },
    { date: '2026-03-06', icon: 'sun', temp: 72 },
    { date: '2026-03-07', icon: 'sun', temp: 74 },
    { date: '2026-03-08', icon: 'sun', temp: 75 },
    { date: '2026-03-09', icon: 'cloud', temp: 73 },
    { date: '2026-03-10', icon: 'cloud', temp: 72 },
];


export const PLANNER_TASKS: LookaheadTask[] = [
  {
    id: 1,
    sNo: 1,
    outline: '3.1',
    name: 'Pave Access Roads',
    taskCode: '32 13 00',
    taskType: 'Normal Task', // Martinez DevelopmentS (GC)
    contractor: 'Martinez DevelopmentS',
    location: 'Building A', // CLASH LOCATION
    progress: 62,
    crewAssigned: 9,
    startDate: '2026-02-12', // CLASH START DATE
    finishDate: '2026-02-20', // CLASH END DATE
    masterStartDate: '2026-02-12',
    masterFinishDate: '2026-02-20',
    isExpanded: true,
    ppcHistory: [82, 85, 78, 88, 92, 90],
    productionQuantity: {
      planned: 1200,
      plannedLocked: true,
      unit: 'CY',
      dailyMetrics: [ // Updated daily metrics to match new task dates
        { date: '2026-02-12', quantity: { plan: 240, actual: 250, unit: 'CY' }, hours: { plan: 8, actual: 8 }, crew: { plan: 9, actual: 9 } },
        { date: '2026-02-13', quantity: { plan: 240, actual: 235, unit: 'CY' }, hours: { plan: 8, actual: 8 }, crew: { plan: 9, actual: 9 } },
        { date: '2026-02-14', quantity: { plan: 240, actual: 240, unit: 'CY' }, hours: { plan: 8, actual: 8 }, crew: { plan: 9, actual: 9 } },
        { date: '2026-02-15', quantity: { plan: 240, actual: 0, unit: 'CY' }, hours: { plan: 8, actual: 0 }, crew: { plan: 9, actual: 0 } },
        { date: '2026-02-16', quantity: { plan: 240, actual: 0, unit: 'CY' }, hours: { plan: 8, actual: 0 }, crew: { plan: 9, actual: 0 } },
        { date: '2026-02-17', quantity: { plan: 240, actual: 0, unit: 'CY' }, hours: { plan: 8, actual: 0 }, crew: { plan: 9, actual: 0 } },
        { date: '2026-02-18', quantity: { plan: 240, actual: 0, unit: 'CY' }, hours: { plan: 8, actual: 0 }, crew: { plan: 9, actual: 0 } },
        { date: '2026-02-19', quantity: { plan: 240, actual: 0, unit: 'CY' }, hours: { plan: 8, actual: 0 }, crew: { plan: 9, actual: 0 } },
        { date: '2026-02-20', quantity: { plan: 240, actual: 0, unit: 'CY' }, hours: { plan: 8, actual: 0 }, crew: { plan: 9, actual: 0 } },
      ],
    },
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Pending, // Set to Pending for initial clash demo status
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.Pending, // Set to Pending for initial clash demo status
    },
    constraints: [
      { type: ConstraintType.RFI, name: 'RFI #001: Foundation Drawings', status: ConstraintStatus.Pending, severity: 'Warning' }
    ],
    manHours: { actual: 120, budget: 200 },
    children: []
  },
  {
    id: 2,
    sNo: 2,
    outline: '3.2',
    name: 'Install Chainlink Fencing',
    taskCode: '32 30 00',
    taskType: 'Normal Task',
    contractor: 'Martinez DevelopmentS',
    location: '',
    progress: 0,
    crewAssigned: 4,
    startDate: '2026-02-04',
    finishDate: '2026-02-18',
    productionQuantity: {
      planned: 500,
      plannedLocked: false,
      unit: 'LF',
      dailyMetrics: [
        { date: '2026-02-04', quantity: { plan: 33.33, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-05', quantity: { plan: 33.34, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-06', quantity: { plan: 33.33, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-07', quantity: { plan: 33.34, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-08', quantity: { plan: 33.33, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-09', quantity: { plan: 33.34, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-10', quantity: { plan: 33.33, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-11', quantity: { plan: 33.34, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-12', quantity: { plan: 33.33, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-13', quantity: { plan: 33.34, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-14', quantity: { plan: 33.33, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-15', quantity: { plan: 33.34, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-16', quantity: { plan: 33.33, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-17', quantity: { plan: 33.34, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-18', quantity: { plan: 33.35, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
      ],
    },
    masterStartDate: '2026-02-04',
    masterFinishDate: '2026-02-18',
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 0, budget: 100 },
  },
  {
    id: 3,
    sNo: 3,
    outline: '3.3',
    name: 'Install Main Gates',
    taskCode: '32 30 00',
    taskType: 'Normal Task', // Martinez DevelopmentS
    contractor: 'Martinez DevelopmentS',
    location: '',
    progress: 33,
    crewAssigned: 6,
    startDate: '2026-02-04',
    finishDate: '2026-02-09',
    masterStartDate: '2026-02-04',
    masterFinishDate: '2026-02-09',
    productionQuantity: {
      planned: 12,
      plannedLocked: true,
      unit: 'EA',
      dailyMetrics: [
        { date: '2026-02-04', quantity: { plan: 2, actual: 2, unit: 'EA' }, hours: { plan: 8, actual: 8 }, crew: { plan: 6, actual: 6 } },
        { date: '2026-02-05', quantity: { plan: 2, actual: 3, unit: 'EA' }, hours: { plan: 8, actual: 8 }, crew: { plan: 6, actual: 6 } },
        { date: '2026-02-06', quantity: { plan: 2, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 6, actual: 0 } },
        { date: '2026-02-07', quantity: { plan: 2, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 6, actual: 0 } },
        { date: '2026-02-08', quantity: { plan: 2, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 6, actual: 0 } },
        { date: '2026-02-09', quantity: { plan: 2, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 6, actual: 0 } },
      ],
    },
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 20, budget: 60 },
  },
  {
    id: 5, // NEW TASK FOR CLASH DEMO
    sNo: 5,
    outline: '3.4',
    name: 'Install Precast Panels',
    taskCode: '03 40 00',
    taskType: 'Normal Task', // Elliott Subcontractors (SC)
    contractor: 'Elliott Subcontractors',
    location: 'Building A', // CLASH LOCATION
    progress: 0,
    crewAssigned: 5,
    startDate: '2026-02-10', // CLASH START DATE
    finishDate: '2026-02-28', // CLASH END DATE
    masterStartDate: '2026-02-10',
    masterFinishDate: '2026-02-28',
    productionQuantity: {
      planned: 95,
      plannedLocked: false,
      unit: 'EA',
      dailyMetrics: [
        { date: '2026-02-10', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-11', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-12', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-13', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-14', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-15', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-16', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-17', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-18', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-19', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-20', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-21', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-22', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-23', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-24', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-25', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-26', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-27', quantity: { plan: 5, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
        { date: '2026-02-28', quantity: { plan: 0, actual: 0, unit: 'EA' }, hours: { plan: 8, actual: 0 }, crew: { plan: 5, actual: 0 } },
      ],
    },
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Pending,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Pending,
      [ConstraintType.Material]: ConstraintStatus.Complete,
    },
    constraints: [
      { type: ConstraintType.Predecessor, name: 'Foundation complete', status: ConstraintStatus.Pending, severity: 'Blocking' }
    ],
    manHours: { actual: 0, budget: 160 },
  },
  {
    id: 7,
    sNo: 7,
    outline: '7.1.1',
    name: 'conduits from floor 1 to 3',
    taskCode: '26 00 00',
    taskType: 'Budget Task', // Elliott Subcontractors
    contractor: 'Elliott Subcontractors',
    location: '',
    progress: 0,
    crewAssigned: 0,
    startDate: '2026-01-20',
    finishDate: '2026-02-09',
    masterStartDate: '2026-01-20',
    masterFinishDate: '2026-02-09',
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Overdue,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.Pending,
    },
    constraints: [
        { type: ConstraintType.Predecessor, name: 'Main Feeder', status: ConstraintStatus.Overdue, severity: 'Blocking' }
    ],
    manHours: { actual: 0, budget: 120 },
  },
  {
    id: 12, // Changed from 8 to 12
    sNo: 12,
    outline: '7.1.2',
    name: 'Building B Internal Wiring',
    taskCode: '26 05 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Elliott Subcontractors',
    location: 'Building B', // CHANGED LOCATION TO AVOID CLASH
    progress: 0,
    crewAssigned: 0,
    startDate: '2026-02-10',
    finishDate: '2026-02-28',
    masterStartDate: '2026-02-10',
    masterFinishDate: '2026-02-28',
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 0, budget: 80 },
  },
  {
    id: 9,
    sNo: 9,
    outline: '7.1.3',
    name: 'Lighting and devices – Floors 1–2',
    taskCode: '26 51 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Elliott Subcontractors',
    location: 'Floors 1-2',
    progress: 0,
    crewAssigned: 0,
    startDate: '2026-03-01',
    finishDate: '2026-03-15',
    masterStartDate: '2026-03-01',
    masterFinishDate: '2026-03-15',
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 0, budget: 60 },
  },
  {
    id: 10,
    sNo: 10,
    outline: '7.1.4',
    name: 'Grounding and bonding',
    taskCode: '26 05 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Elliott Subcontractors',
    location: 'Site Wide',
    progress: 0,
    crewAssigned: 0,
    startDate: '2026-02-15',
    finishDate: '2026-02-22',
    masterStartDate: '2026-02-15',
    masterFinishDate: '2026-02-22',
    productionQuantity: {
      planned: 800,
      plannedLocked: true,
      unit: 'LF',
      dailyMetrics: [
        { date: '2026-02-15', quantity: { plan: 100, actual: 112, unit: 'LF' }, hours: { plan: 8, actual: 9 }, crew: { plan: 4, actual: 4 } },
        { date: '2026-02-16', quantity: { plan: 100, actual: 98, unit: 'LF' }, hours: { plan: 8, actual: 8 }, crew: { plan: 4, actual: 4 } },
        { date: '2026-02-17', quantity: { plan: 100, actual: 105, unit: 'LF' }, hours: { plan: 8, actual: 8 }, crew: { plan: 4, actual: 4 } },
        { date: '2026-02-18', quantity: { plan: 100, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-19', quantity: { plan: 100, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-20', quantity: { plan: 100, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-21', quantity: { plan: 100, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
        { date: '2026-02-22', quantity: { plan: 100, actual: 0, unit: 'LF' }, hours: { plan: 8, actual: 0 }, crew: { plan: 4, actual: 0 } },
      ],
    },
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 0, budget: 40 },
  },
  {
    id: 11,
    sNo: 11,
    outline: '7.1.5',
    name: 'Fire alarm devices – Zone A',
    taskCode: '28 31 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Elliott Subcontractors',
    location: 'Zone A',
    progress: 0,
    crewAssigned: 0,
    startDate: '2026-03-10',
    finishDate: '2026-03-20',
    masterStartDate: '2026-03-10',
    masterFinishDate: '2026-03-20',
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 0, budget: 50 },
  },
];

export const MASTER_SCHEDULE_TASKS: LookaheadTask[] = [
  {
    id: 'm1',
    sNo: 1,
    outline: '1',
    name: 'Preconstruction & Mobilization',
    taskCode: '01 89 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Martinez DevelopmentS',
    location: 'Site Wide',
    progress: 100,
    crewAssigned: 2,
    startDate: '2026-01-02',
    finishDate: '2026-01-03',
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 16, budget: 16 },
  },
  {
    id: 'm2',
    sNo: 2,
    outline: '1.1',
    name: 'Site Survey & Geotechnical Investigation',
    taskCode: '01 89 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Martinez DevelopmentS',
    location: 'Site Wide',
    progress: 100,
    crewAssigned: 2,
    startDate: '2026-01-02',
    finishDate: '2026-01-03',
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 32, budget: 32 },
  },
  {
    id: 'm3',
    sNo: 3,
    outline: '1.2',
    name: 'Building Permits & Approval',
    taskCode: '01 89 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Martinez DevelopmentS',
    location: 'Office',
    progress: 100,
    crewAssigned: 1,
    startDate: '2026-01-02',
    finishDate: '2026-01-03',
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 16, budget: 16 },
  },
  {
    id: 'm4',
    sNo: 4,
    outline: '2',
    name: 'Site Setup',
    taskCode: '31 10 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Martinez DevelopmentS',
    location: 'Site Wide',
    progress: 100,
    crewAssigned: 4,
    startDate: '2026-01-06',
    finishDate: '2027-01-07',
    slack: 12,
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 2800, budget: 2856 },
  },
  {
    id: 'm5',
    sNo: 5,
    outline: '2.1',
    name: 'Site Clearance & Grubbing',
    taskCode: '31 10 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Martinez DevelopmentS',
    location: 'Zone A',
    progress: 100,
    crewAssigned: 6,
    startDate: '2026-01-06',
    finishDate: '2026-01-08',
    slack: 5,
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 144, budget: 144 },
  },
  {
    id: 'm6',
    sNo: 6,
    outline: '4',
    name: 'Earthwork & Foundations',
    taskCode: '00 01 01',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Mora Specialty Contractors',
    location: 'Foundation',
    progress: 100,
    crewAssigned: 12,
    startDate: '2026-02-07',
    finishDate: '2026-04-10',
    isCriticalPath: true,
    slack: 0,
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 2911, budget: 2911 },
  },
  {
    id: 'm7',
    sNo: 7,
    outline: '4.2.1',
    name: 'Foundation Footings',
    taskCode: '31 00 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Mora Specialty Contractors',
    location: 'Foundation',
    progress: 100,
    crewAssigned: 8,
    startDate: '2026-03-10',
    finishDate: '2026-03-27',
    slack: 2,
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 1120, budget: 1120 },
  },
  {
    id: 'm8',
    sNo: 8,
    outline: '4.3',
    name: 'Structure',
    taskCode: '31 00 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Mora Specialty Contractors',
    location: 'Building A',
    progress: 80,
    crewAssigned: 15,
    startDate: '2026-04-11',
    finishDate: '2026-09-12',
    isCriticalPath: true,
    slack: 0,
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 18000, budget: 23349 },
  },
  {
    id: 'm9',
    sNo: 9,
    outline: '4.3.1',
    name: 'Column Starter Bars from 1 to 3 floor',
    taskCode: '31 00 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Mora Specialty Contractors',
    location: 'Floors 1-3',
    progress: 100,
    crewAssigned: 6,
    startDate: '2026-04-11',
    finishDate: '2026-09-12',
    slack: 8,
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Complete,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.OnSite,
    },
    constraints: [],
    manHours: { actual: 2160, budget: 2160 },
  },
  {
    id: 'm10',
    sNo: 10,
    outline: '4.4',
    name: 'Roof',
    taskCode: '31 00 00',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Mora Specialty Contractors',
    location: 'Roof',
    progress: 0,
    crewAssigned: 10,
    startDate: '2026-07-28',
    finishDate: '2026-08-22',
    isCriticalPath: true,
    slack: 0,
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Pending,
      [ConstraintType.RFI]: ConstraintStatus.Pending,
      [ConstraintType.Submittal]: ConstraintStatus.Complete,
      [ConstraintType.Material]: ConstraintStatus.Pending,
    },
    constraints: [
      { type: ConstraintType.Predecessor, name: 'Structure Completion', status: ConstraintStatus.Pending, severity: 'Blocking' },
      { type: ConstraintType.RFI, name: 'RFI #104: Roof Drain Detail', status: ConstraintStatus.Pending, severity: 'Warning' }
    ],
    manHours: { actual: 0, budget: 3656 },
  },
  {
    id: 'm11',
    sNo: 11,
    outline: '5',
    name: 'Masonry & Walling',
    taskCode: '00 01 01',
    taskType: 'Normal Task', // Elliott Subcontractors
    contractor: 'Farley Structures',
    location: 'Building A',
    progress: 0,
    crewAssigned: 8,
    startDate: '2026-02-10',
    finishDate: '2026-04-14',
    slack: 15,
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Pending,
      [ConstraintType.RFI]: ConstraintStatus.Complete,
      [ConstraintType.Submittal]: ConstraintStatus.Pending,
      [ConstraintType.Material]: ConstraintStatus.Pending,
    },
    constraints: [
      { type: ConstraintType.Submittal, name: 'SUB #042: Brick Sample Approval', status: ConstraintStatus.Pending, severity: 'Warning' }
    ],
    manHours: { actual: 0, budget: 1274 },
  },
  {
    id: 'm12',
    sNo: 12,
    outline: '6',
    name: 'Electrical',
    taskCode: '26 00 00',
    taskType: 'Budget Task',
    contractor: 'Elliott Subcontractors',
    location: 'Building A',
    progress: 0,
    crewAssigned: 4,
    startDate: '2026-03-01',
    finishDate: '2026-05-27',
    isCriticalPath: true,
    slack: 0,
    status: {
      [ConstraintType.Predecessor]: ConstraintStatus.Pending,
      [ConstraintType.RFI]: ConstraintStatus.Pending,
      [ConstraintType.Submittal]: ConstraintStatus.Pending,
      [ConstraintType.Material]: ConstraintStatus.Pending,
    },
    constraints: [
      { type: ConstraintType.RFI, name: 'RFI #112: Panel Location Conflict', status: ConstraintStatus.Pending, severity: 'Blocking' },
      { type: ConstraintType.Submittal, name: 'SUB #088: Switchgear Shop Drawings', status: ConstraintStatus.Pending, severity: 'Blocking' }
    ],
    manHours: { actual: 0, budget: 435 },
  }
];
